"""empty message

Revision ID: 743aef82a5d5
Revises: 376d9b709a13
Create Date: 2024-10-29 03:03:53.023944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '743aef82a5d5'
down_revision: Union[str, None] = '376d9b709a13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('img_path', sa.String(), nullable=False))
    op.drop_column('product', 'img')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('img', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('product', 'img_path')
    # ### end Alembic commands ###
